name: "Build Artifacts for RetroDECK main manifest"

on:
  push:
    branches:
      - master
      - main
  workflow_call:
  workflow_dispatch:

env:
  MANIFEST_FILENAME: "net.rpcs3.RPCS3.yaml"

jobs:
  install-dependencies:
    uses: RetroDECK/components-template/.github/workflows/install_dependencies.yml@main

  build-project:
    needs: install-dependencies  # Ensures this job only runs after install-dependencies
    uses: RetroDECK/components-template/.github/workflows/build_artifacts.yml@main