name: "Build Artifacts for RetroDECK main manifest"

on:
  push:
    branches:
      - master
      - main
  workflow_call:
  workflow_dispatch:

jobs:

  repo-clone:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

  build-project:
    uses: RetroDECK/components-template/.github/workflows/build_artifacts.yml@main
    needs: repo-clone
    with:
        MANIFEST_FILENAME: "net.rpcs3.RPCS3.yaml"