name: "Build Artifacts for RetroDECK main manifest"

on:
  push:
    branches:
      - master
      - main
  workflow_call:

jobs:
  install-dependencies:
    uses: RetroDECK/components-template/.github/workflows/install_dependencies.yml@main
    with:
      # You can pass inputs here if the `install_dependencies.yml` workflow defines them

  build-project:
    needs: install-dependencies  # Ensures this job only runs after install-dependencies
    uses: RetroDECK/components-template/.github/workflows/build_artifacts.yml@main
    with:
      # Pass inputs as needed if the `build_artifacts.yml` workflow defines them
